/* ═══════════════════════════════════════════════════════════════════════
   JARVIS avatar — a lightweight 2D "arc core" face.
   Canvas 2D, capped at 30 fps, pauses when the page is hidden.
   States: idle · listening · thinking · speaking · sleeping · muted
           happy · confused · error (transient overlays over the base state)
   ═══════════════════════════════════════════════════════════════════════ */
(function () {
  "use strict";

  const canvas = document.getElementById("face");
  if (!canvas) return;
  const ctx = canvas.getContext("2d");

  const AV = {
    state: "IDLE",          // IDLE | LISTENING | THINKING | SPEAKING | SLEEPING | MUTED
    level: 0,               // live mic level 0..1 (listening)
    viseme: { level: 0, openness: 0, width: 0 },   // current mouth frame (speaking)
    muted: false,
    expression: null,       // 'happy' | 'confused' | 'error' | null
    exprUntil: 0,
    style: "face",          // 'face' | 'core'
  };

  window.JarvisAvatar = AV;

  // ── animation state ────────────────────────────────────────────────────
  let t = 0;                 // seconds since start
  let last = performance.now();
  let acc = 0;
  let blinkT = 0, nextBlink = 2 + Math.random() * 3;
  let blinkPhase = 0;        // 0..1..0 while blinking
  let glanceX = 0, glanceY = 0, tgtGX = 0, tgtGY = 0, nextGlance = 4;
  let dispLevel = 0, dispOpen = 0, dispWide = 0;
  let exprUntilT = 0;        // expiry on THIS module's clock (see setExpression)
  let running = true, pageVisible = true;

  // ── living-motion engine ──────────────────────────────────────────────────
  // A presence is not a fixed picture: it drifts, leans, breathes and leans
  // INTO what it is doing. Everything here is generated by layered sine noise
  // (never random jumps — random is jerky) and integrated through critically-
  // damped springs, so the core can never teleport and always glides home.
  // The same numbers drive the canvas drawing AND the CSS vars, so the HUD
  // core and the face move as one body.
  const MOTION = {
    // spring integrator state (position + velocity per channel; velocity
    // fields are named `<channel>v` because spring() addresses them that way)
    x: 0, xv: 0,          // gentle left/right drift   (fraction of R)
    y: 0, yv: 0,          // slight vertical movement  (fraction of R)
    z: 0, zv: 0,          // subtle forward/backward   (fraction of R)
    tilt: 0, tiltv: 0,    // small rotation/tilt       (radians)
    pulse: 0, pulsev: 0,  // voice-driven scale swell  (fraction)
    // published (clamped) values read by render() and the CSS vars
    cx: 0, cy: 0, cz: 0, rot: 0, swell: 1,
  };
  // Critically-damped spring: pos += vel*dt; vel += (target-pos)*k*dt - vel*d*dt.
  // Never overshoots into oscillation, never snaps — the response the brief
  // calls "fluid, organic, never robotic". Non-finite values self-heal to
  // rest, so a poisoned channel can never stick or throw downstream.
  function spring(ch, target, dt, stiffness, damping) {
    if (!isFinite(MOTION[ch])) MOTION[ch] = 0;
    if (!isFinite(MOTION[ch + "v"])) MOTION[ch + "v"] = 0;
    MOTION[ch + "v"] += (target - MOTION[ch]) * stiffness * dt;
    MOTION[ch + "v"] *= Math.max(0, 1 - damping * dt);
    MOTION[ch] += MOTION[ch + "v"] * dt;
    return MOTION[ch];
  }
  // Layered incommensurate sines — the cheapest smooth pseudo-noise that never
  // repeats visibly. Two frequencies with an irrational-ish ratio per channel
  // means the sum drifts unpredictably but CONTINUOUSLY (organic, not random).
  function drift(t, a, b, phase) {
    return 0.62 * Math.sin(t * a + phase) + 0.38 * Math.sin(t * b + phase * 1.7);
  }
  // Speech intensity → motion energy. Quiet voice stays nearly still; normal
  // speech breathes; excited speech leans into the room. Smoothed by the
  // caller (dispLevel is already eased), so this maps, not jumps.
  function motionEnergy(level) {
    return Math.min(1, level * 1.15);        // 0..1 with a little headroom
  }
  let energy = 0;              // smoothed 0..1 driving every channel's amplitude
  let energySlow = 0;          // slower follower — separates swell from sway

  const TAU = Math.PI * 2;
  const ease = (a, b, k) => a + (b - a) * Math.min(1, Math.max(0, k));

  // State → colour
  function palette() {
    switch (AV.state) {
      case "LISTENING": return { main: "#38bdf8", glow: "rgba(56,189,248," };
      case "THINKING":  return { main: "#8b6df5", glow: "rgba(139,109,245," };
      case "SPEAKING":  return { main: "#7dd7fc", glow: "rgba(125,215,252," };
      case "SLEEPING":  return { main: "#2c3a55", glow: "rgba(84,110,160," };
      case "MUTED":     return { main: "#8b5a68", glow: "rgba(255,92,122," };
      default:          return { main: "#38bdf8", glow: "rgba(56,189,248," };
    }
  }
  function exprPalette(p) {
    if (AV.expression === "happy")    return { main: "#6fe6c2", glow: "rgba(111,230,194," };
    if (AV.expression === "confused") return { main: "#f5b45c", glow: "rgba(245,180,92," };
    if (AV.expression === "error")    return { main: "#ff5c7a", glow: "rgba(255,92,122," };
    return p;
  }

  // ── expressions ────────────────────────────────────────────────────────
  // app.js used to set AV.exprUntil = performance.now()/1000 + 3 (epoch) while
  // this loop compares against its own `t` (seconds since boot) — expressions
  // could never expire and the face stayed happy/confused forever. Callers now
  // use setExpression, which expires on the clock the renderer actually uses.
  AV.setExpression = function (expr, seconds) {
    const map = { playful: "happy", surprised: "confused", sad: "confused" };
    AV.expression = map[expr] || expr || null;
    exprUntilT = t + Math.max(0.5, Number(seconds) || 3);
    AV.exprUntil = exprUntilT;          // kept in sync for any external reader
  };

  // ── viseme scheduling (mirrors backend push_visemes semantics) ────────
  let vFrames = null, vHop = 0, vStart = 0;
  AV.pushVisemes = function (frames, hop, at) {
    vFrames = frames; vHop = hop || 0.02; vStart = at;
  };
  function tickVisemes(nowSec) {
    if (!vFrames || !vFrames.length || AV.state !== "SPEAKING") {
      AV.viseme.level = ease(AV.viseme.level, 0, 0.25);
      AV.viseme.openness = ease(AV.viseme.openness, 0, 0.25);
      AV.viseme.width = ease(AV.viseme.width, 0, 0.25);
      return;
    }
    let idx = Math.floor((nowSec - vStart) / vHop);
    if (idx < 0) idx = 0;
    if (idx >= vFrames.length) idx = vFrames.length - 1;
    const f = vFrames[idx];
    if (Array.isArray(f)) {
      AV.viseme.level    = f[0] || 0;
      AV.viseme.openness = f[1] || 0;
      AV.viseme.width    = f[2] || 0;
    }
  }

  // ── drawing helpers ───────────────────────────────────────────────────
  function ring(cx, cy, r, a0, a1, width, color, blur) {
    ctx.beginPath();
    ctx.arc(cx, cy, r, a0, a1);
    ctx.lineWidth = width;
    ctx.strokeStyle = color;
    ctx.shadowColor = color;
    ctx.shadowBlur = blur || 0;
    ctx.stroke();
    ctx.shadowBlur = 0;
  }

  function drawWaveRing(cx, cy, rBase, amp, color, phase, n) {
    // circle of radial bars — the "waveform halo"
    n = n || 64;
    ctx.save();
    for (let i = 0; i < n; i++) {
      const a = (i / n) * TAU - Math.PI / 2;
      const wobble =
        0.30 + 0.70 * Math.abs(
          Math.sin(i * 1.7 + phase * 2.1) * 0.5 +
          Math.sin(i * 3.3 - phase * 3.7) * 0.35 +
          Math.sin(i * 0.7 + phase * 1.3) * 0.3
        );
      const len = 3 + amp * 30 * wobble;
      const x0 = cx + Math.cos(a) * rBase;
      const y0 = cy + Math.sin(a) * rBase;
      const x1 = cx + Math.cos(a) * (rBase + len);
      const y1 = cy + Math.sin(a) * (rBase + len);
      ctx.beginPath();
      ctx.moveTo(x0, y0); ctx.lineTo(x1, y1);
      ctx.lineWidth = 2;
      ctx.lineCap = "round";
      ctx.strokeStyle = color;
      ctx.globalAlpha = 0.25 + 0.55 * (len / 33);
      ctx.stroke();
    }
    ctx.restore();
    ctx.globalAlpha = 1;
  }

  // ── main render ───────────────────────────────────────────────────────
  function render() {
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    // A hidden view (Settings, a minimised window) has no layout box, and
    // writing that 0 straight into canvas.width used to lock the canvas at
    // 0x0 FOREVER — the face went permanently blank and silent the first time
    // the stage lost its box. No box ⇒ keep the last frame and skip the draw;
    // the backing store only ever mirrors a real box.
    const cssW = canvas.clientWidth, cssH = canvas.clientHeight;
    if (cssW < 2 || cssH < 2) return;
    const bw = Math.max(1, Math.round(cssW * dpr));
    const bh = Math.max(1, Math.round(cssH * dpr));
    if (canvas.width !== bw || canvas.height !== bh) {
      canvas.width = bw;
      canvas.height = bh;
    }
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.clearRect(0, 0, cssW, cssH);

    const W = cssW, H = cssH;
    const R0 = Math.min(W, H) * 0.36;
    // ── living presence: the whole drawing breathes as one body ──────────
    // MOTION is eased in the frame loop (springs over layered sine noise),
    // so cx/cy glide and can never jump. cz leans the presence toward/away
    // from you, swell is the voice-driven breath in its size — all clamped
    // to a few percent of the stage (see the clamps in frame()).
    const cx = W / 2 + glanceX * W * 0.015 + MOTION.cx * R0;
    const cy = H / 2 + glanceY * H * 0.015 + MOTION.cy * R0;
    const R = R0 * MOTION.swell * (1 + MOTION.cz);

    // ── MINIMAL mode: one calm core + one soft ring, nothing else.
    //    The cheapest possible living avatar (~5 draw calls, 30 fps cap).
    if (AV.style === "minimal") {
      const p = palette();
      const breathe = 0.02 * Math.sin(t * 1.3);
      const amp = AV.state === "LISTENING" ? dispLevel :
                  AV.state === "SPEAKING"  ? Math.max(dispLevel, AV.viseme.level) : 0;
      const r = R * (0.72 + breathe + amp * 0.05);
      const aura = ctx.createRadialGradient(cx, cy, r * 0.15, cx, cy, r * 1.5);
      aura.addColorStop(0, p.glow + "0.07)");
      aura.addColorStop(1, p.glow + "0)");
      ctx.fillStyle = aura;
      ctx.beginPath(); ctx.arc(cx, cy, r * 1.5, 0, TAU); ctx.fill();
      const cg = ctx.createRadialGradient(cx, cy, r * 0.1, cx, cy, r);
      cg.addColorStop(0, p.glow + "0.8)");
      cg.addColorStop(1, p.glow + "0.05)");
      ctx.fillStyle = cg;
      ctx.beginPath(); ctx.arc(cx, cy, r, 0, TAU); ctx.fill();
      ring(cx, cy, r * 1.18, 0, TAU, 1.6, p.glow + "0.35)", 0);
      if (AV.muted) {
        ring(cx, cy, r * 1.30, Math.PI * 0.62, Math.PI * 0.88, 3,
             "rgba(255,92,122,0.85)", 6);
      }
      return;
    }

    // ── ORBIT mode: a tiny pulsing sun with satellites on tilted rings.
    //    Pure motion, no face — reads as "system activity at a glance".
    if (AV.style === "orbit") {
      const p = palette();
      const amp = AV.state === "LISTENING" ? dispLevel :
                  AV.state === "SPEAKING"  ? Math.max(dispLevel, AV.viseme.level) : 0;
      const spin = AV.state === "THINKING" ? t * 2.2 : t * 0.5;
      // centre
      const coreR = R * (0.16 + amp * 0.05 + 0.012 * Math.sin(t * 2.4));
      const cg = ctx.createRadialGradient(cx, cy, 0, cx, cy, coreR * 2.2);
      cg.addColorStop(0, p.glow + "0.9)");
      cg.addColorStop(0.5, p.glow + "0.25)");
      cg.addColorStop(1, p.glow + "0)");
      ctx.fillStyle = cg;
      ctx.beginPath(); ctx.arc(cx, cy, coreR * 2.2, 0, TAU); ctx.fill();
      // three tilted orbit rings with satellites
      const orbits = [
        { r: 0.52, tilt: -0.45, speed: 1.0,  sats: 2 },
        { r: 0.78, tilt: 0.30,  speed: -0.6, sats: 3 },
        { r: 1.02, tilt: -0.12, speed: 0.35, sats: 1 },
      ];
      for (const o of orbits) {
        const rr = R * o.r;
        ctx.save();
        ctx.translate(cx, cy);
        ctx.rotate(o.tilt);
        ctx.beginPath();
        ctx.ellipse(0, 0, rr, rr * 0.36, 0, 0, TAU);
        ctx.lineWidth = 1.1;
        ctx.strokeStyle = p.glow + "0.28)";
        ctx.stroke();
        for (let s = 0; s < o.sats; s++) {
          const a = spin * o.speed + (s / o.sats) * TAU;
          const sx = Math.cos(a) * rr, sy = Math.sin(a) * rr * 0.36;
          const sg = ctx.createRadialGradient(sx, sy, 0, sx, sy, 5.5);
          sg.addColorStop(0, "#ffffff");
          sg.addColorStop(0.4, p.glow + "0.95)");
          sg.addColorStop(1, p.glow + "0)");
          ctx.fillStyle = sg;
          ctx.beginPath(); ctx.arc(sx, sy, 5.5, 0, TAU); ctx.fill();
        }
        ctx.restore();
      }
      if (AV.muted) {
        ring(cx, cy, R * 1.14, Math.PI * 0.62, Math.PI * 0.88, 3,
             "rgba(255,92,122,0.85)", 6);
      }
      return;
    }

    // ── HELIX mode: a rotating double helix of dots with rungs — the
    //    "genome of thoughts". Twist tightens with the audio level.
    if (AV.style === "helix") {
      const p = palette();
      const amp = AV.state === "LISTENING" ? dispLevel :
                  AV.state === "SPEAKING"  ? Math.max(dispLevel, AV.viseme.level) : 0;
      const spin = AV.state === "THINKING" ? t * 2.6 : t * 0.9;
      const H2 = R * 2.1;
      const N = 26;
      const twist = 2.6 + amp * 2.2;          // radians over the strand
      const pts = [[], []];
      for (let s = 0; s < 2; s++) {
        for (let i = 0; i < N; i++) {
          const f = i / (N - 1);              // 0..1 along the strand
          const y = cy - H2 / 2 + f * H2;
          const a = spin + f * twist * Math.PI + s * Math.PI;
          const depth = 0.5 + 0.5 * Math.sin(a);      // -1..1 → fake z
          const x = cx + Math.cos(a) * R * 0.52;
          pts[s].push({ x, y, depth });
        }
      }
      // rungs first (behind the dots)
      ctx.lineWidth = 1;
      for (let i = 0; i < N; i += 2) {
        const a1 = pts[0][i], b1 = pts[1][i];
        const al = 0.10 + 0.25 * (a1.depth + b1.depth) / 2;
        ctx.strokeStyle = p.glow + al.toFixed(3) + ")";
        ctx.beginPath(); ctx.moveTo(a1.x, a1.y); ctx.lineTo(b1.x, b1.y); ctx.stroke();
      }
      // dots — depth sorts size and alpha, giving real parallax feel
      for (let s = 0; s < 2; s++) {
        for (const q of pts[s]) {
          const d = (q.depth + 1) / 2;        // 0 back .. 1 front
          const rr = 1.4 + d * 2.4 + amp * 1.6;
          ctx.fillStyle = p.glow + (0.18 + 0.72 * d).toFixed(3) + ")";
          ctx.beginPath(); ctx.arc(q.x, q.y, rr, 0, TAU); ctx.fill();
        }
      }
      if (AV.muted) {
        ring(cx, cy, R * 1.16, Math.PI * 0.62, Math.PI * 0.88, 3,
             "rgba(255,92,122,0.85)", 6);
      }
      return;
    }

    let p = exprPalette(palette());

    // A slight body tilt for the rest of this branch — applied around the
    // core's own centre and unwound by the one shared restore at the end.
    ctx.save();
    ctx.translate(cx, cy);
    ctx.rotate(MOTION.rot);
    ctx.translate(-cx, -cy);

    // breathing / activity scale
    const breathe = 0.018 * Math.sin(t * 1.4);
    const amp =
      AV.state === "LISTENING" ? dispLevel :
      AV.state === "SPEAKING"  ? Math.max(dispLevel, AV.viseme.level) : 0;
    const scale = 1 + breathe + amp * 0.03;
    const r = R * scale;

    // special expressions tint
    if (AV.expression === "error") {
      const pulse = 0.5 + 0.5 * Math.sin(t * 6);
      p = { main: p.main, glow: p.glow };
      ctx.globalAlpha = 0.5 + 0.2 * pulse;
    }

    // outer soft aura — very subtle, never neon
    const aura = ctx.createRadialGradient(cx, cy, r * 0.2, cx, cy, r * 1.45);
    aura.addColorStop(0, p.glow + "0.055)");
    aura.addColorStop(1, p.glow + "0)");
    ctx.fillStyle = aura;
    ctx.beginPath(); ctx.arc(cx, cy, r * 1.45, 0, TAU); ctx.fill();

    // segmented outer ring (slow rotation; fast while thinking)
    const segN = 48;
    const rot = AV.state === "THINKING" ? t * 1.6 : t * 0.12;
    for (let i = 0; i < segN; i++) {
      const a0 = (i / segN) * TAU + rot;
      const a1 = a0 + (TAU / segN) * 0.55;
      const alpha = 0.10 + 0.4 * amp * ((i % 4) / 3);
      ring(cx, cy, r * 1.06, a0, a1, 2, p.glow + alpha + ")", 0);
    }

    // orbit arcs
    const orbAmp = 0.5 + amp * 0.9;
    ring(cx, cy, r * 0.88, t * 0.9, t * 0.9 + 1.15 * orbAmp, 2.6, p.glow + "0.6)", 5);
    ring(cx, cy, r * 0.88, t * 0.9 + Math.PI, t * 0.9 + Math.PI + 1.15 * orbAmp, 2.6, p.glow + "0.6)", 5);
    ring(cx, cy, r * 0.72, -t * 1.3, -t * 1.3 + 0.8 * orbAmp, 1.8, p.glow + "0.35)", 3);
    ring(cx, cy, r * 0.72, -t * 1.3 + Math.PI * 1.2, -t * 1.3 + Math.PI * 1.2 + 0.8 * orbAmp, 1.8, p.glow + "0.35)", 3);

    // core — a calm luminous disc, no harsh hotspot
    const coreR = r * 0.52 * (AV.state === "SLEEPING" ? 0.8 : 1);
    const cg = ctx.createRadialGradient(cx, cy, coreR * 0.08, cx, cy, coreR);
    const bright = 0.62 + amp * 0.35 + (AV.expression === "happy" ? 0.12 : 0);
    cg.addColorStop(0, p.glow + (0.85 * bright) + ")");
    cg.addColorStop(0.55, p.glow + (0.30 * bright) + ")");
    cg.addColorStop(1, p.glow + "0.04)");
    ctx.fillStyle = cg;
    ctx.beginPath(); ctx.arc(cx, cy, coreR, 0, TAU); ctx.fill();

    // inner highlight ring instead of a hot white centre
    ring(cx, cy, coreR * 0.66, 0, TAU, 1.2, p.glow + "0.5)", 4);

    // core rim
    ring(cx, cy, coreR, 0, TAU, 1.6, p.glow + "0.7)", 6);

    // face features (only in 'face' style)
    if (AV.style !== "core") {
      const eyeY = cy - coreR * 0.28;
      const eyeDX = coreR * 0.42;
      const eyeR = coreR * 0.11;

      // blink
      let eyeSquish = 1;
      if (AV.state === "SLEEPING") eyeSquish = 0.08;
      else if (blinkPhase > 0) eyeSquish = Math.max(0.08, Math.abs(1 - blinkPhase * 2));

      // eyes: small glowing dots
      for (const s of [-1, 1]) {
        const ex = cx + s * eyeDX + glanceX * coreR * 0.10;
        const ey = eyeY + glanceY * coreR * 0.08;
        ctx.save();
        ctx.translate(ex, ey);
        ctx.scale(1, eyeSquish);
        const eg = ctx.createRadialGradient(0, 0, 0, 0, 0, eyeR);
        eg.addColorStop(0, "#ffffff");
        eg.addColorStop(0.5, p.glow + "0.95)");
        eg.addColorStop(1, p.glow + "0.1)");
        ctx.fillStyle = eg;
        ctx.beginPath(); ctx.arc(0, 0, eyeR, 0, TAU); ctx.fill();
        ctx.restore();
      }

      // brows — ride the expression
      const browY = eyeY - coreR * (AV.expression === "confused" ? 0.34 : 0.30);
      ctx.lineWidth = 2.4; ctx.lineCap = "round";
      ctx.strokeStyle = p.glow + "0.7)";
      for (const s of [-1, 1]) {
        ctx.beginPath();
        const tilt = AV.expression === "confused" ? s * 0.16 : 0;
        ctx.moveTo(cx + s * eyeDX - coreR * 0.16, browY + tilt * coreR);
        ctx.lineTo(cx + s * eyeDX + coreR * 0.16, browY - tilt * coreR);
        ctx.stroke();
      }

      // mouth — a rounded arc, invisible at rest (no blob when closed)
      const open = AV.state === "SPEAKING" ? dispOpen : 0;
      const wide = AV.state === "SPEAKING" ? dispWide : 0;
      const mY = cy + coreR * 0.42;
      const mW = coreR * (0.34 + wide * 0.24);
      const mH = coreR * (0.04 + open * 0.5);
      ctx.beginPath();
      if (mH < 2.2) {
        // closed mouth: a gentle smile-line (middle sits just below the ends)
        ctx.moveTo(cx - mW, mY);
        ctx.quadraticCurveTo(cx, mY + coreR * 0.08, cx + mW, mY);
        ctx.lineWidth = 1.8;
        ctx.lineCap = "round";
        ctx.strokeStyle = p.glow + "0.55)";
        ctx.stroke();
      } else {
        ctx.ellipse(cx, mY, mW, mH, 0, 0, TAU);
        ctx.fillStyle = p.glow + (0.22 + open * 0.45) + ")";
        ctx.fill();
        ctx.lineWidth = 1.6;
        ctx.strokeStyle = p.glow + "0.7)";
        ctx.stroke();
      }
    } else {
      // 'core' style — inner reactor filaments instead of a face
      ctx.save();
      ctx.translate(cx, cy);
      ctx.rotate(-t * 0.6);
      for (let i = 0; i < 8; i++) {
        ctx.rotate(TAU / 8);
        ctx.beginPath();
        ctx.moveTo(coreR * 0.18, 0);
        ctx.lineTo(coreR * 0.95, 0);
        ctx.lineWidth = 2;
        ctx.strokeStyle = p.glow + (0.22 + amp * 0.5) + ")";
        ctx.stroke();
      }
      ctx.restore();
    }

    // muted indicator
    if (AV.muted) {
      ring(cx, cy, r * 1.14, Math.PI * 0.62, Math.PI * 0.88, 3, "rgba(255,92,122,0.85)", 6);
    }

    // waveform halo while listening/speaking
    if (AV.state === "LISTENING" || AV.state === "SPEAKING") {
      drawWaveRing(cx, cy, r * 1.13, dispLevel * (AV.state === "SPEAKING" ? Math.max(AV.viseme.level, 0.15) : 1),
                   p.glow + "0.55)", t, 56);
    }

    ctx.globalAlpha = 1;
    ctx.restore();          // unwind the living-tilt transform
  }

  // ── loop (adaptive frame budget, pauses when hidden) ──────────────────
  // Full rate only while JARVIS is actually working or sound is coming in;
  // a calm 15 fps when it is merely idling, and a slow drift for reduced
  // motion. The animation clock still advances in real time, so nothing
  // changes speed — a low-end PC just draws fewer frames.
  const mqReduce = window.matchMedia
    ? window.matchMedia("(prefers-reduced-motion: reduce)") : null;
  function fpsCap() {
    if (mqReduce && mqReduce.matches) return 8;
    const loud = Math.max(dispLevel, AV.viseme.level) > 0.05;
    if (AV.state === "THINKING" || AV.state === "SPEAKING" || loud) return 30;
    return 15;
  }

  function frame(now) {
    requestAnimationFrame(frame);
    if (!running || !pageVisible) return;
    const dt = Math.min(0.1, (now - last) / 1000);
    last = now; t += dt;

    // expressions expire (on this module's clock)
    if (AV.expression && t > exprUntilT) AV.expression = null;

    // blink timer
    blinkT += dt;
    if (blinkT > nextBlink) { blinkT = 0; nextBlink = 2.2 + Math.random() * 3.4; blinkPhase = 0.001; }
    if (blinkPhase > 0) {
      blinkPhase += dt * 6.5;
      if (blinkPhase >= 1) blinkPhase = 0;
    }

    // idle glances
    if (t > nextGlance) {
      nextGlance = t + 3 + Math.random() * 5;
      tgtGX = (Math.random() - 0.5) * 1.6;
      tgtGY = (Math.random() - 0.5) * 1.0;
    }
    glanceX = ease(glanceX, tgtGX, dt * 2.4);
    glanceY = ease(glanceY, tgtGY, dt * 2.4);

    // smoothed levels
    const target = AV.state === "LISTENING" ? AV.level : AV.viseme.level;
    dispLevel = ease(dispLevel, target, dt * 10);
    dispOpen  = ease(dispOpen, AV.viseme.openness, dt * 14);
    dispWide  = ease(dispWide, AV.viseme.width, dt * 14);

    // ── living motion: one energy signal, five spring channels ─────────────
    // Per state: idle breathes, listening attends (leans in, holds still-ish),
    // thinking wanders slowly and intelligently, speaking rides the voice.
    // Every channel integrates through a spring, so state changes blend and
    // the core always glides back toward centre — it can never jump or wander
    // away (targets are clamped well inside the stage).
    const lvl = Math.max(dispLevel, AV.viseme.level);
    energy = ease(energy, motionEnergy(lvl), dt * 3.2);      // fast swell
    energySlow = ease(energySlow, energy, dt * 1.4);         // slow body follow

    // energy targets per state (tiny on purpose — presence, not pogo)
    let tx = 0, ty = 0, tz = 0, tTilt = 0, tPulse = 0;
    if (AV.state === "SPEAKING") {
      // speech drives everything, scaled by loudness; slow head-bob rhythm
      // plus a beat-level shimmer so excited speech genuinely moves more
      const e = energy, es = energySlow;
      tx   = drift(t, 0.9, 0.41, 0.0) * (0.020 + e * 0.052);
      ty   = drift(t, 0.7, 1.3,  2.1) * (0.012 + e * 0.030)
           + Math.sin(t * 3.1) * e * 0.010;                   // talking nods
      tz   = drift(t, 0.5, 0.33, 4.2) * (0.014 + e * 0.046); // forward/back
      tTilt= drift(t, 0.6, 0.29, 1.3) * (0.010 + es * 0.030);
      tPulse = 0.010 + e * 0.055;                            // scale with intensity
    } else if (AV.state === "LISTENING") {
      // attentive: nearly still, a slow lean toward "you" and a small
      // pulse with the USER's voice level — it visibly listens
      tx   = drift(t, 0.5, 0.23, 5.0) * 0.012;
      ty   = drift(t, 0.4, 0.19, 1.8) * 0.008 + 0.004;       // slight lean in
      tz   = 0.006 + dispLevel * 0.012;
      tTilt= drift(t, 0.4, 0.17, 3.3) * 0.008;
      tPulse = 0.006 + dispLevel * 0.020;
    } else if (AV.state === "THINKING") {
      // slow intelligent ambient: longer excursions, very slow, tilted focus
      tx   = drift(t, 0.33, 0.13, 2.6) * 0.022;
      ty   = drift(t, 0.27, 0.11, 4.9) * 0.014;
      tz   = drift(t, 0.21, 0.09, 0.7) * 0.016;
      tTilt= drift(t, 0.3, 0.12, 5.5) * 0.018;
      tPulse = 0.004 + 0.004 * Math.sin(t * 0.8);
    } else {
      // idle / sleeping: soft breathing and a lazy orbit, almost imperceptible
      tx   = drift(t, 0.4, 0.17, 1.1) * 0.014;
      ty   = drift(t, 0.31, 0.14, 3.8) * 0.010;
      tz   = drift(t, 0.24, 0.10, 2.2) * 0.010;
      tTilt= drift(t, 0.35, 0.15, 0.4) * 0.012;
      tPulse = 0.004 + 0.004 * Math.sin(t * 0.9);
    }

    // springs: stiffness/damping tuned per channel — position glide, tilt lazy,
    // pulse quick enough to ride syllables without flicker
    const mx = spring("x", tx, dt, 2.2, 3.4);
    const my = spring("y", ty, dt, 2.4, 3.6);
    const mz = spring("z", tz, dt, 1.8, 3.0);
    const mTilt = spring("tilt", tTilt, dt, 1.6, 2.6);
    const mPulse = spring("pulse", tPulse, dt, 6.0, 5.0);

    // publish for render() and the CSS side (clamped: never drift far)
    MOTION.cx = Math.max(-0.09, Math.min(0.09, mx));
    MOTION.cy = Math.max(-0.07, Math.min(0.07, my));
    MOTION.cz = Math.max(-0.06, Math.min(0.06, mz));
    MOTION.rot = Math.max(-0.06, Math.min(0.06, mTilt));   // radians
    MOTION.swell = 1 + Math.max(-0.02, Math.min(0.09, mPulse));

    // voice-reactive room glow: the ambient core behind the face breathes
    // with the actual mic/voice level, and its two lobes ride the viseme
    // channels — tall lobe with jaw openness, wide lobe with mouth width.
    // The vars live on the stage so the HUD (VU meter, halo, readouts) reads
    // the same numbers without any extra bookkeeping.
    const varHost = document.getElementById("faceStage") ||
                    document.getElementById("hudCoreGlow");
    if (varHost) {
      const lv = Math.max(dispLevel, AV.viseme.level);
      varHost.style.setProperty("--voice", lv.toFixed(3));
      varHost.style.setProperty("--open", dispOpen.toFixed(3));
      varHost.style.setProperty("--wide", dispWide.toFixed(3));
      // living motion, shared with the HUD: the same springs that move the
      // drawn core also carry the decorative HUD core, so the whole presence
      // leans, drifts and swells as ONE body. Applied as a transform on the
      // readouts' parent chain via CSS (see .hud-core-glow) — computed here
      // once per frame, never per element.
      varHost.style.setProperty("--mx", (isFinite(MOTION.cx) ? MOTION.cx : 0).toFixed(4));
      varHost.style.setProperty("--my", (isFinite(MOTION.cy) ? MOTION.cy : 0).toFixed(4));
      varHost.style.setProperty("--mz", (isFinite(MOTION.cz) ? MOTION.cz : 0).toFixed(4));
      varHost.style.setProperty("--mrot", (isFinite(MOTION.rot) ? MOTION.rot : 0).toFixed(4));
      varHost.style.setProperty("--mswell", (isFinite(MOTION.swell - 1) ? MOTION.swell - 1 : 0).toFixed(4));
    }

    acc += dt;
    if (acc >= 1 / fpsCap()) { acc = 0; tickVisemes(t); render(); }
  }
  requestAnimationFrame(frame);

  // pause rendering when the page is hidden or window minimised
  document.addEventListener("visibilitychange", () => {
    pageVisible = !document.hidden;
    last = performance.now();
  });
  window.addEventListener("blur",  () => { /* keep last frame; still cheap */ });

  AV.setPaused = function (p) { running = !p; last = performance.now(); };

  // Show/hide without tearing down the mode (the settings toggle used to only
  // affect the 3D avatar — the 2D face ignored it entirely).
  AV.setVisible = function (v) {
    canvas.style.visibility = v ? "" : "hidden";
  };
})();
